/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as AdminSalesRouteImport } from './routes/admin/sales'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminSettingsTrackingRouteImport } from './routes/admin/settings/tracking'
import { Route as AdminSettingsSeoRouteImport } from './routes/admin/settings/seo'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminProductsCreateRouteImport } from './routes/admin/products/create'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsTrackingRoute = AdminSettingsTrackingRouteImport.update({
  id: '/settings/tracking',
  path: '/settings/tracking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsSeoRoute = AdminSettingsSeoRouteImport.update({
  id: '/settings/seo',
  path: '/settings/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsCreateRoute = AdminProductsCreateRouteImport.update({
  id: '/products/create',
  path: '/products/create',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/formations': typeof FormationsRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/sales': typeof AdminSalesRoute
  '/history/$id': typeof HistoryIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/settings/seo': typeof AdminSettingsSeoRoute
  '/admin/settings/tracking': typeof AdminSettingsTrackingRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/formations': typeof FormationsRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/sales': typeof AdminSalesRoute
  '/history/$id': typeof HistoryIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/settings/seo': typeof AdminSettingsSeoRoute
  '/admin/settings/tracking': typeof AdminSettingsTrackingRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/formations': typeof FormationsRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/sales': typeof AdminSalesRoute
  '/history/$id': typeof HistoryIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/create': typeof AdminProductsCreateRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/settings/seo': typeof AdminSettingsSeoRoute
  '/admin/settings/tracking': typeof AdminSettingsTrackingRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/formations'
    | '/login'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/sales'
    | '/history/$id'
    | '/admin/'
    | '/admin/products/create'
    | '/admin/products/new'
    | '/admin/settings/seo'
    | '/admin/settings/tracking'
    | '/admin/products/'
    | '/admin/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/formations'
    | '/login'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/sales'
    | '/history/$id'
    | '/admin'
    | '/admin/products/create'
    | '/admin/products/new'
    | '/admin/settings/seo'
    | '/admin/settings/tracking'
    | '/admin/products'
    | '/admin/settings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/formations'
    | '/login'
    | '/admin/analytics'
    | '/admin/customers'
    | '/admin/sales'
    | '/history/$id'
    | '/admin/'
    | '/admin/products/create'
    | '/admin/products/new'
    | '/admin/settings/seo'
    | '/admin/settings/tracking'
    | '/admin/products/'
    | '/admin/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FormationsRoute: typeof FormationsRoute
  LoginRoute: typeof LoginRoute
  HistoryIdRoute: typeof HistoryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/tracking': {
      id: '/admin/settings/tracking'
      path: '/settings/tracking'
      fullPath: '/admin/settings/tracking'
      preLoaderRoute: typeof AdminSettingsTrackingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/seo': {
      id: '/admin/settings/seo'
      path: '/settings/seo'
      fullPath: '/admin/settings/seo'
      preLoaderRoute: typeof AdminSettingsSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/create': {
      id: '/admin/products/create'
      path: '/products/create'
      fullPath: '/admin/products/create'
      preLoaderRoute: typeof AdminProductsCreateRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductsCreateRoute: typeof AdminProductsCreateRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminSettingsSeoRoute: typeof AdminSettingsSeoRoute
  AdminSettingsTrackingRoute: typeof AdminSettingsTrackingRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductsCreateRoute: AdminProductsCreateRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminSettingsSeoRoute: AdminSettingsSeoRoute,
  AdminSettingsTrackingRoute: AdminSettingsTrackingRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FormationsRoute: FormationsRoute,
  LoginRoute: LoginRoute,
  HistoryIdRoute: HistoryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
